// Install REST Client by Huachao Mao in VSCode to send these off from here

// Check DB updates via prisma view 'make view-db'

// ========== BASIC SERVER ========== //

// See if server is alive and kicking
http://localhost:3000
###

// ========== LOCATION ========== //

// Get all locations
http://localhost:3000/location
###

// Create new location
POST http://localhost:3000/location HTTP/1.1
content-type: application/json

{
    "authorId": 1,
	"name": "Richardplatz 24",
	"city": "Berlin",
	"country": "Germany",
	"longitude": "52.474823",
	"latitude": "13.447864",
	"isPublic": true
}
###

// ========== USERS ========== //

// Get all users
http://localhost:3000/users
###


// Create new user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "22",
    "email": "tester_v332@grit.com"
}
###

// ========== EVENTS ========== //

// Get all published events
http://localhost:3000/events
###

// Get event by event id
http://localhost:3000/events/1
###

// Search for event by string
http://localhost:3000/events?search=Sack
###

// Create event, use Alice email from seed
POST http://localhost:3000/events HTTP/1.1
content-type: application/json

{
    "authorId": 1,
    "title": "Sackhüpfen",
    "startAt": "2026-05-01T18:00:00Z",
    "endAt": "2026-05-02T02:00:00Z",
    "isPublic": false,
	"locationId": 2
}
###

PATCH http://localhost:3000/events/1 HTTP/1.1
content-type: application/json

{
    "endAt": "2025-01-02T02:00:33Z",
    "isPublished": true
}
###

// Delete event
DELETE http://localhost:3000/events/1 HTTP/1.1
###
