// Install REST Client by Huachao Mao in VSCode to send these off from here

// Check DB updates via prisma view 'make view-db'

@baseUrl = http://localhost:3000

# ========== HEALTH CHECK ==========
GET {{baseUrl}}
###

# ========== USER ONBOARDING ==========

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
	"name": "test8",
	"email": "test8@example.com",
	"password": "password123"
}
###

# Confirm Email
# Replace the 'token' value with the one you see in Mailtrap or the DB
@confToken =14baa7811e83aac0f4cc9264d57f81f53d010bc933f79e478d52ead940abba08
GET {{baseUrl}}/auth/confirm?token={{confToken}}
###

// ========== AUTHENTICATION ========== //

# Get token of user 1
# @name debugGetToken
GET {{baseUrl}}/auth/debug/token/1
###

// Normal login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
	"email": "alice@example.com",
	"password": "password123"
}
###

// Admin login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
	"email": "admin@example.com",
	"password": "admin123"
}
###

# Capture the token from response automatically
#@token = {{debugGetToken.response.body.accessToken}}
@token = {{login.response.body.accessToken}}

# Verify/Rehydrate Current User
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
###

# ========== USER ACTIONS ==========

# Get all users
GET {{baseUrl}}/users
###

# Get all users with limit set to 1
GET {{baseUrl}}/users?limit=1
###

# Get all users with a valid cursor (starting from user 2).
GET {{baseUrl}}/users?cursor=MjAyNi0wMS0yN1QxNDozMDoxMi40NjFafDE=
###

# Get My Events (Attending)
GET {{baseUrl}}/users/me/events
Authorization: Bearer {{token}}
###

# Get My Private Events (Attending, invited)
GET {{baseUrl}}/users/me/events/private
Authorization: Bearer {{token}}
###


# User attends an event
PATCH {{baseUrl}}/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "attending": {
    "connect": [4]
  }
}
###

# Delete logged in user
DELETE {{baseUrl}}/users/me
Authorization: Bearer {{token}}
###

# ========== LOCATION ========== //

# Get all locations
GET {{baseUrl}}/locations
###

# Get all locations with limit set to 1
GET {{baseUrl}}/locations?limit=1
###

# Create new location
POST {{baseUrl}}/locations
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name": "Aaa",
	"city": "Berlin",
	"country": "Germany",
	"longitude": 59.4748,
	"latitude": 11.4478,
	"isPublic": false
}
###

// Delete location
DELETE {{baseUrl}}/locations/1 HTTP/1.1
Authorization: Bearer {{token}}
###

// ========== EVENTS ========== //

# Get all published events
GET {{baseUrl}}/events
###

// Search for event by string
GET {{baseUrl}}/events?search=app
###

// Search for event by limit and start time
GET {{baseUrl}}/events?limit=1&start_from=2026-01-24
###

// Search for second event by using limit and cursor
GET {{baseUrl}}/events?limit=1&cursor=MjAyNi0wMS0yNFQxMjowMDowMC4wMDBafDQ=
###

# Get event by event id
GET {{baseUrl}}/events/2
###

// Create event, use to whatever user the token resolves to
POST {{baseUrl}}/events HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"title": "Party at unkown's place!",
	"startAt": "2026-05-01T18:00:00Z",
	"endAt": "2026-05-02T02:00:00Z",
	"isPublic": false,
	"isPublished": true
}
###

# Update event (using ID 1)
PATCH {{baseUrl}}/events/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"endAt": "2025-01-02T02:00:33Z",
	"locationId": 2,
	"isPublic": false
}
###

# Delete event (using ID 4)
DELETE {{baseUrl}}/events/4 HTTP/1.1
Authorization: Bearer {{token}}
###

// ========== FRIENDS ========== //

# Send friend request
POST {{baseUrl}}/users/me/friends/requests HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"receiverId": 6

}
###

# List incoming friend requests
GET {{baseUrl}}/users/me/friends/requests/incoming?limit=1 HTTP/1.1
Authorization: Bearer {{token}}
###

# List outgoing friend requests
GET {{baseUrl}}/users/me/friends/requests/outgoing?limit=1 HTTP/1.1
Authorization: Bearer {{token}}
###

# List friends
GET {{baseUrl}}/users/me/friends?limit=10 HTTP/1.1
Authorization: Bearer {{token}}
###

# Accept friend request
POST {{baseUrl}}/users/me/friends/requests/90e4c37a-f7af-4319-9485-a08e2dd71cef/accept HTTP/1.1
Authorization: Bearer {{token}}
###

# Decline friend request
POST {{baseUrl}}/users/me/friends/requests/64ff0ec9-e768-4b78-95fe-31863d8ab5ae/decline HTTP/1.1
Authorization: Bearer {{token}}
###

# Remove friend
DELETE {{baseUrl}}/users/me/friends/2 HTTP/1.1
Authorization: Bearer {{token}}
###

// ========== EVENT INVITES ========== //

# Send event invite
POST {{baseUrl}}/users/me/invites HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"receiverId": "2",
	"eventId": "4"
}
###

# Accept/decline event invite
POST {{baseUrl}}/users/me/invites/c7c4bc33-a038-462e-a9f9-4cf5b6f0aa52 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"status": "ACCEPTED"
}
###

# Delete event invite
DELETE {{baseUrl}}/users/me/invites/0ea182e7-e062-44b2-b93d-9cea44347661
Authorization: Bearer {{token}}
###

# Get list of incoming event invites
GET {{baseUrl}}/users/me/invites/incoming HTTP/1.1
Authorization: Bearer {{token}}
###

# Get list of outgoing event invites
GET {{baseUrl}}/users/me/invites/outgoing HTTP/1.1
Authorization: Bearer {{token}}
###

// ========== ADMIN ========== //

# Get ALL users (sorted by name, asc)
GET {{baseUrl}}/users/admin
Authorization: Bearer {{token}}
###

# Get ALL locations (sorted by name, asc)
GET {{baseUrl}}/locations/admin
Authorization: Bearer {{token}}
###

# Get ALL events (sorted by startAt, asc)
GET {{baseUrl}}/events/admin
Authorization: Bearer {{token}}
###

# Update event by event id
PATCH {{baseUrl}}/events/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"endAt": "2025-01-02T02:00:33Z",
	"locationId": 2
}
###

# Delete event image by event id
DELETE {{baseUrl}}/events/1/image HTTP/1.1
Authorization: Bearer {{token}}
###

# Delete event file by event id and file id
DELETE {{baseUrl}}/events/1/files/1 HTTP/1.1
Authorization: Bearer {{token}}
###

# Delete event by event id
DELETE {{baseUrl}}/events/3 HTTP/1.1
Authorization: Bearer {{token}}
###

# Delete a user by user id
DELETE {{baseUrl}}/users/3 HTTP/1.1
Authorization: Bearer {{token}}
###

# Delete a user avatar by user id
DELETE {{baseUrl}}/users/2/avatar HTTP/1.1
Authorization: Bearer {{token}}
###

# Patch a user by user id (name or "attending")
PATCH {{baseUrl}}/users/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cindy",
  "attending": {
    "disconnect": [3]
  }
}
###

# Delete a location by location id
DELETE {{baseUrl}}/locations/2
Authorization: Bearer {{token}}
###
