// Install REST Client by Huachao Mao in VSCode to send these off from here

// Check DB updates via prisma view 'make view-db'

// 1. Fix bug for show all published events.

// ========== BASIC SERVER ========== //

// See if server is alive and kicking
http://localhost:3000
###


// ========== AUTHENTICATOION ========== //

// Get Token for user 1
GET http://localhost:3000/auth/debug/token/1
###

// Set the variable (Remove the 'Bearer' prefix here, add it in the request)
#@token = JWT_TOKE_HERE

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJpYXQiOjE3Njg4NDkxNjYsImV4cCI6MTc2OTQ1Mzk2Nn0.TxJkAl0A1-y1SY0rrUX_l6HJFPKOsZcoVVOj2vXvoNw

// ========== LOCATION ========== //

// Get all locations
http://localhost:3000/locations
###

// Create new location
POST http://localhost:3000/locations HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "authorId": 1,
	"name": "Richardunkown 42",
	"city": "Berlin",
	"country": "Germany",
	"longitude": 59.474823,
	"latitude": 11.447864,
	"isPublic": true
}
###

// Delete location
DELETE http://localhost:3000/locations/1 HTTP/1.1
Authorization: Bearer {{token}}
###


// ========== USERS ========== //

// Get all users
http://localhost:3000/users
###


// Create new user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "Thomas Test",
    "email": "tester_v332@grit.com"
}
###

// User attends an event
PATCH http://localhost:3000/users/attend HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"attending": 2
}
###

// ========== EVENTS ========== //

// Get all published events
http://localhost:3000/events
###

// Get event by event id
http://localhost:3000/events/1
###

// Search for event by string
http://localhost:3000/events?search=Sack
###

// Create event, use to whatever user the token resolves to
POST http://localhost:3000/events HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "title": "Party at unkown's place!",
    "startAt": "2026-05-01T18:00:00Z",
    "endAt": "2026-05-02T02:00:00Z",
    "isPublic": true,
	"isPublished": true
}
###

PATCH http://localhost:3000/events/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "endAt": "2025-01-02T02:00:33Z",
	"locationId": 1
}
###

// Delete event
DELETE http://localhost:3000/events/4 HTTP/1.1
Authorization: Bearer {{token}}
###
