// Install REST Client by Huachao Mao in VSCode to send these off from here

// Check DB updates via prisma view 'make view-db'

@baseUrl = http://localhost:3000

# ========== HEALTH CHECK ==========
GET {{baseUrl}}
###

# ========== USER ONBOARDING ==========

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
	"email": "test@example.com",
	"password": "password123"
}
###

# Confirm Email
# Replace the 'token' value with the one you see in Mailtrap or the DB
@confToken =14baa7811e83aac0f4cc9264d57f81f53d010bc933f79e478d52ead940abba08
GET {{baseUrl}}/auth/confirm?token={{confToken}}
###

// ========== AUTHENTICATION ========== //

# Get token of user 1
# @name debugGetToken
GET {{baseUrl}}/auth/debug/token/1
###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
	"email": "cindy@example.com",
	"password": "0123456789"
}
###

# Capture the token from response automatically
#@token = {{debugGetToken.response.body.accessToken}}
@token = {{login.response.body.accessToken}}

# Verify/Rehydrate Current User
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
###

# ========== USER ACTIONS ==========

# Get all users
GET {{baseUrl}}/users
###

# Get all users with limit set to 1
GET {{baseUrl}}/users?limit=1
###

# Get all users with a valid cursor (starting from user 2).
GET {{baseUrl}}/users?cursor=MjAyNi0wMS0yN1QxNDozMDoxMi40NjFafDE=
###

# Get My Events (Attending)
GET {{baseUrl}}/users/me/events
Authorization: Bearer {{token}}
###

# User attends an event
PATCH {{baseUrl}}/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"attending": 2
}
###

# ========== LOCATION ========== //

# Get all locations
GET {{baseUrl}}/locations
###

# Get all locations with limit set to 1
GET {{baseUrl}}/locations?limit=1
###

# Create new location
POST {{baseUrl}}/locations
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"authorId": 1,
	"name": "Secret Lair",
	"city": "Berlin",
	"country": "Germany",
	"longitude": 59.4748,
	"latitude": 11.4478,
	"isPublic": true
}
###

// Delete location
DELETE {{baseUrl}}/locations/6 HTTP/1.1
Authorization: Bearer {{token}}
###

// ========== EVENTS ========== //

# Get all published events
GET {{baseUrl}}/events
###

// Search for event by string
GET {{baseUrl}}/events?search=app
###

// Search for event by limit and start time
GET {{baseUrl}}/events?limit=1&start_from=2026-01-24
###

// Search for second event by using limit and cursor
GET {{baseUrl}}/events?limit=1&cursor=MjAyNi0wMS0yNFQxMjowMDowMC4wMDBafDQ=
###

# Get event by event id
GET {{baseUrl}}/events/2
###

// Create event, use to whatever user the token resolves to
POST {{baseUrl}}/events HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"title": "Party at unkown's place!",
	"startAt": "2026-05-01T18:00:00Z",
	"endAt": "2026-05-02T02:00:00Z",
	"isPublic": true,
	"isPublished": true
}
###

# Update event (using ID 1)
PATCH {{baseUrl}}/events/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"endAt": "2025-01-02T02:00:33Z",
	"locationId": 2
}
###

# Delete event (using ID 4)
DELETE {{baseUrl}}/events/4 HTTP/1.1
Authorization: Bearer {{token}}
###

// ========== FRIENDS ========== //

# Send friend request
POST {{baseUrl}}/users/me/friends/requests HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
	"receiverId": 7

}
###

# List incoming friend requests
GET {{baseUrl}}/users/me/friends/requests/incoming HTTP/1.1
Authorization: Bearer {{token}}
###

# List outgoing friend requests
GET {{baseUrl}}/users/me/friends/requests/outgoing HTTP/1.1
Authorization: Bearer {{token}}
###

# List friends
GET {{baseUrl}}/users/me/friends HTTP/1.1
Authorization: Bearer {{token}}
###

# Accept friend request
POST {{baseUrl}}/users/me/friends/requests/edb8ea35-b508-4bef-b4f1-7a03d77b95d7/accept HTTP/1.1
Authorization: Bearer {{token}}
###

# Decline friend request
POST {{baseUrl}}/users/me/friends/requests/ada2ba69-b7c8-41eb-bc72-3a8ceef974eb/decline HTTP/1.1
Authorization: Bearer {{token}}
###

# Remove friend
DELETE {{baseUrl}}/users/me/friends/3 HTTP/1.1
Authorization: Bearer {{token}}
###